# Generated by Django 3.2.8 on 2022-02-02 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_rubric_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='articles.author', verbose_name='Выберете автора'),
        ),
        migrations.AlterField(
            model_name='article',
            name='rubric',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='articles.rubric', verbose_name='Рубрики'),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(default='', help_text='Ссылка, например: about', unique=True, verbose_name='URL-aдрес(Cлаг)'),
        ),
        migrations.AlterField(
            model_name='rubric',
            name='slug',
            field=models.SlugField(default='', help_text='Ссылка, например: about', unique=True, verbose_name='URL-aдрес(Cлаг)'),
        ),
    ]
