# Generated by Django 3.2.8 on 2022-02-02 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20220202_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='cover',
            field=models.ImageField(blank=True, help_text='Не обязательно', null=True, upload_to='article_cover/%Y/%m/%d/', verbose_name='Обложка статьи'),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(help_text='Пример: Игумен Феофан (Кузнецов)', max_length=70, unique=True, verbose_name='Фамилия и имя'),
        ),
        migrations.AlterField(
            model_name='rubric',
            name='name',
            field=models.CharField(db_index=True, help_text='Пример: Новости Обители', max_length=50, verbose_name='Название рубрики'),
        ),
    ]
