# Generated by Django 3.2.8 on 2022-02-06 12:50

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_alter_article_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content_2',
            field=django_quill.fields.QuillField(default=''),
        ),
    ]
