# Generated by Django 3.2.8 on 2022-02-06 18:24

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_article_content_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content_3',
            field=tinymce.models.HTMLField(default=''),
        ),
    ]
