# Generated by Django 3.2.8 on 2022-02-10 22:21

from django.db import migrations, models
import filebrowser.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_auto_20220208_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubric',
            name='order',
            field=models.PositiveSmallIntegerField(db_index=True, default=1, help_text='Выберете позицию для сортировки', verbose_name='Позиция'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=filebrowser.fields.FileBrowseField(blank=True, max_length=200, verbose_name='Изображение'),
        ),
    ]
