# Generated by Django 3.2.8 on 2022-02-27 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_alter_rubric_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.TextField(max_length=500, verbose_name='Краткое описание'),
        ),
    ]
