# Generated by Django 3.2.8 on 2022-02-27 17:13

from django.db import migrations, models
import filebrowser.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Сarousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default='', help_text='Ссылка, например: /about/history/', unique=True, verbose_name='URL-aдрес(Cлаг)')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, max_length=500, verbose_name='Краткое описание')),
                ('order', models.PositiveSmallIntegerField(db_index=True, default=1, help_text='Выберете позицию для сортировки', verbose_name='Позиция')),
                ('image', filebrowser.fields.FileBrowseField(max_length=200, verbose_name='Обложка')),
            ],
            options={
                'verbose_name': 'Настройка Карусели',
                'verbose_name_plural': 'Настройка Карусели',
                'ordering': ['-order'],
            },
        ),
    ]
