# Generated by Django 3.2.8 on 2022-02-27 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='сarousel',
            name='slug',
        ),
        migrations.AddField(
            model_name='сarousel',
            name='url',
            field=models.CharField(db_index=True, default='', help_text='Ссылка, например: /about/history/', max_length=100, verbose_name='URL'),
        ),
    ]
