# Generated by Django 3.2.8 on 2022-02-28 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220227_2019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='сarousel',
            name='description',
        ),
    ]
