# Generated by Django 3.2.12 on 2022-03-06 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_сarousel_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='сarousel',
            options={'ordering': ['order'], 'verbose_name': 'Карусель', 'verbose_name_plural': 'Настройка карусели'},
        ),
        migrations.AlterField(
            model_name='сarousel',
            name='order',
            field=models.PositiveSmallIntegerField(db_index=True, default=1, help_text='Выберете позицию для сортировки', unique=True, verbose_name='Позиция'),
        ),
    ]
