# Generated by Django 3.2.8 on 2022-01-16 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Название должно быль уникальным', max_length=50, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(help_text='Ссылка, например: about', unique=True, verbose_name='URL-aдрес(Cлаг)')),
                ('description', models.TextField(blank=True, help_text='Не обязательное поле', verbose_name='Описание')),
                ('order', models.PositiveSmallIntegerField(db_index=True, default=1, help_text='Выберете позицию для сортировки', verbose_name='Позиция')),
                ('hide', models.BooleanField(default=False, verbose_name='Скрыть')),
            ],
            options={
                'verbose_name': 'Меню',
                'verbose_name_plural': 'Меню',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, help_text='Не обязательное поле', verbose_name='Описание')),
                ('slug', models.SlugField(help_text='Ссылка, например: about', unique=True, verbose_name='URL-aдрес(Cлаг)')),
                ('order', models.PositiveSmallIntegerField(db_index=True, default=1, help_text='Выберете позицию для сортировки', verbose_name='Позиция')),
                ('hide', models.BooleanField(default=False, verbose_name='Скрыть')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nav.menu')),
            ],
            options={
                'verbose_name': 'Пункт меню',
                'verbose_name_plural': 'Пункты меню',
                'ordering': ['order', 'title'],
            },
        ),
    ]
