# Generated by Django 3.2.8 on 2022-02-02 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nav', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='description',
            field=models.TextField(blank=True, help_text='Не обязательное поле', max_length=200, verbose_name='Описание'),
        ),
    ]
