# Generated by Django 3.2.8 on 2022-02-15 06:28

from django.db import migrations
import filebrowser.fields


class Migration(migrations.Migration):

    dependencies = [
        ('nav', '0002_alter_menuitem_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='image',
            field=filebrowser.fields.FileBrowseField(blank=True, max_length=200, verbose_name='Изображение'),
        ),
    ]
