# Generated by Django 3.2.8 on 2022-02-27 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nav', '0003_menuitem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='description',
            field=models.TextField(blank=True, help_text='Не обязательное поле', max_length=500, verbose_name='Описание'),
        ),
    ]
