# Generated by Django 3.2.8 on 2022-01-15 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListChurchService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20, verbose_name='Название')),
                ('hide', models.BooleanField(default=False, verbose_name='Скрыть')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Церковные службы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(db_index=True, help_text='Введите дату', unique=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Расписание',
                'ordering': ['day'],
            },
        ),
        migrations.CreateModel(
            name='TimeTableItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(null=True, verbose_name='Время')),
                ('text', models.TextField(blank=True, verbose_name='Дополнительная информация')),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.timetable')),
                ('service', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='timetable.listchurchservice', verbose_name='Выберете службу')),
            ],
            options={
                'verbose_name': 'Богослужение',
                'verbose_name_plural': 'Богослужения',
                'ordering': ['date', 'time'],
            },
        ),
    ]
