# Generated by Django 3.2.8 on 2022-02-27 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='name_holiday',
            field=models.CharField(blank=True, max_length=50, verbose_name='Название праздника'),
        ),
    ]
