# Generated by Django 3.2.8 on 2022-02-27 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_timetable_name_holiday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='name_holiday',
            field=models.CharField(blank=True, max_length=100, verbose_name='Название праздника'),
        ),
    ]
